export const developers = [
  {
    id: 1,
    name: "Arjun Mehta",
    role: "Full Stack",
    stack: "React",
    avatar: "🧑‍💻",
    github: "@arjunmehta",
    memberSince: "Jan 2025",
  },
  {
    id: 2,
    name: "Priya Sharma",
    role: "Frontend",
    stack: "Vue",
    avatar: "👩‍💻",
    github: "@priyasharma",
    memberSince: "Mar 2025",
  },
  {
    id: 3,
    name: "Rahul",
    role: "Backend",
    stack: "Go",
    avatar: "🧑‍🔧",
    github: "@rahuldev",
    memberSince: "Feb 2025",
  },
];

export const projects = [
  {
    id: 1,
    title: "OpenSource Kanban",
    slug: "opensource-kanban",
    tagline:
      "A lightweight, open-source project management tool designed for small dev teams. Think Trello — but self-hosted, fully customizable, and built by the community.",
    description: `Most teams either pay for Jira (overengineered) or use sticky notes (chaos). OpenSource Kanban fills the gap: a simple, self-hostable board with drag-and-drop cards, labels, due dates, and team assignments. Built in the open, deployable in minutes.`,
    tags: ["React", "Node.js", "MongoDB", "Socket.io"],
    category: "Productivity",
    level: "Intermediate",
    hoursPerWeek: "10–15 hrs/week",
    applicants: 4,
    teamSize: "3–5 people",
    timeline: "3–4 months",
    status: "OPEN",
    postedAgo: "2 days ago",
    author: developers[0],
    rolesNeeded: ["React Developer", "UI/UX Designer"],
    features: [
      "Drag-and-drop Kanban board",
      "Label, priority & due date system",
      "Activity log per card",
      "Real-time updates via Socket.io",
      "Team member assignment",
      "REST API for integrations",
    ],
    milestones: [
      { label: "Core board UI", done: true },
      { label: "Backend API", done: true },
      { label: "Real-time sync", done: false },
      { label: "Auth & teams", done: false },
      { label: "Public launch", done: false },
    ],
    whoWeAreLookingFor: `A React dev who's comfortable with drag-and-drop libraries (react-beautiful-dnd or dnd-kit) and a designer who can clean up the UI. You don't need to be senior — curiosity and consistency matter more.`,
    github: "https://github.com",
  },
  {
    id: 2,
    title: "DevBlog CMS",
    slug: "devblog-cms",
    tagline:
      "Markdown-first blogging platform with syntax highlighting and SEO baked in from day one.",
    description: `Most blogging platforms treat code as an afterthought. DevBlog CMS is built for developers — Markdown-native, with syntax highlighting, code blocks, and SEO metadata all first-class citizens.`,
    tags: ["Next.js", "MDX", "PostgreSQL", "Vercel"],
    category: "Developer Tools",
    level: "Beginner",
    hoursPerWeek: "5–10 hrs/week",
    applicants: 2,
    teamSize: "2–3 people",
    timeline: "2–3 months",
    status: "OPEN",
    postedAgo: "5 days ago",
    author: developers[1],
    rolesNeeded: ["Full Stack Developer", "Technical Writer"],
    features: [
      "MDX-powered content",
      "Syntax highlighting",
      "SEO metadata built-in",
      "RSS feed generation",
      "Tag & category system",
      "Draft/publish workflow",
    ],
    milestones: [
      { label: "Core MDX setup", done: true },
      { label: "Syntax highlighting", done: false },
      { label: "SEO module", done: false },
      { label: "Admin panel", done: false },
      { label: "Public launch", done: false },
    ],
    whoWeAreLookingFor: `Someone who loves clean writing tools and knows Next.js. Bonus points for MDX experience.`,
    github: "https://github.com",
  },
  {
    id: 3,
    title: "CLI Toolchain Manager",
    slug: "cli-toolchain-manager",
    tagline:
      "Unified manager for dev CLI tools — think nvm but for everything. Needs a Rust dev.",
    description: `Managing multiple CLI tool versions is painful. CLI Toolchain Manager aims to be a single binary that handles installs, updates, and version pinning for any dev tool — node, python, go, rust, you name it.`,
    tags: ["Rust", "WASM", "Shell", "CLI"],
    category: "DevOps",
    level: "Advanced",
    hoursPerWeek: "15–20 hrs/week",
    applicants: 1,
    teamSize: "2 people",
    timeline: "4–6 months",
    status: "OPEN",
    postedAgo: "1 week ago",
    author: developers[2],
    rolesNeeded: ["Rust Developer", "DevOps Engineer"],
    features: [
      "Single binary distribution",
      "Version pinning per project",
      "Shell integration (bash/zsh/fish)",
      "Offline mode",
      "Plugin architecture",
      "Cross-platform support",
    ],
    milestones: [
      { label: "Core resolver", done: true },
      { label: "Node.js support", done: false },
      { label: "Python support", done: false },
      { label: "Shell hooks", done: false },
      { label: "Plugin API", done: false },
    ],
    whoWeAreLookingFor: `An experienced Rust developer who cares about developer experience. You should be comfortable with async Rust and have an opinion about CLI design.`,
    github: "https://github.com",
  },
];

export const stats = {
  developers: 3,
  projects: 2,
  collaborations: 1,
  skillsListed: 5,
};
